name: Print App Name

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'The name of your application'
        required: true
        type: string
        default: 'My Default App'

jobs:
  print-app-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print App Name
        run: echo "The application name is ${{ inputs.app_name }}"
